apiVersion: apps/v1
kind: Deployment
metadata:
  name: syntaxnow-assets
spec:
  template:
    spec:
      containers:
        - name: syntaxnow-assets
          image: "ghcr.io/syntaxnow-labs/syntaxnow-assets:main-eb6be94"
