apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prod-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/syntaxnow-labs/gitops.git
    targetRevision: main
    path: platform/namespaces/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true