apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-api-service
spec:
  template:
    spec:
      containers:
        - name: mock-api-service
          image: "ghcr.io/syntaxnow-labs/mock-api-service:dev-6fe2844"
