apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-react-app
spec:
  template:
    spec:
      containers:
        - name: sample-react-app
          image: "ghcr.io/syntaxnow-labs/sample-react-app:main-aa75afd851b8d3aaf24e3b8acd358f9b50ad0593"
